#!/bin/bash
# Return the path of the file specified by the region, season and variable
# If nothing is returned, it means the file does not exist
#
#
if [ "$#" -ne "3" ]; then
  echo "Usage:    get_4D_filename region season variable"
  echo "Example:    get_4D_filename Arctic Summer chlorophyll"
  exit 1
fi

datadir="/data/EMODnet/Chemistry"

region="$1"
season="$2"
variable="$3"
# Variable name should be one of these:
# ammonium chlorophyll nitrogen oxygen phosphate silicate

# Check if root directory exists, otherwise exits
if [ ! -d "${datadir}" ]; then
  echo "Data directory doesn't exist, exiting script"
  exit 1
fi

# Find the file according to argins
filepath=$(find ${datadir}/${region}*/${season}*/ -type f -name *${variable}*.4Danl.nc)

# Check if results is not empty
if [[ ${#filepath} == 0 ]]; then
  echo "No file found"
else
  echo ${filepath}
fi
