"""
# Add the correct DOI to each file

DOI's were sent by Eugenia 
"""

using NCDatasets
using Dates
using Glob
using DIVAnd
using Test

# User inputs
# ------------

hostname = gethostname()
if hostname == "ogs04"
	@info "Working in production server"
	databasedir = "/production/apache/data/emodnet-domains/By sea regions/Black Sea"
elseif hostname == "GHER-ULg-Laptop"
	outputbasedir = "/data/EMODnet/Chemistry/merged/"
	databasedir = "/data/EMODnet/Chemistry/prod/"
elseif hostname == "gherdivand"
	outputbasedir = "/home/ctroupin/data/EMODnet/merged"
	databasedir = "/home/ctroupin/data/EMODnet/By sea regions"
else
	@error("Unknown host")
end

function edit_global_att(datafile::String)
    NCDatasets.Dataset(datafile, "a") do ds
      ds.attrib["Conventions"] = "CF-1.6" ;
      ds.attrib["product_version"] = "2.0" ;
      ds.attrib["source"] = "Observational data from SeaDataNet/EMODnet Chemistry Data Network" ;
      ds.attrib["bathymetry_source"] = "The GEBCO 30sec Digital Atlas published by the British Oceanographic Data Centre on behalf of IOC and IHO, 2003" ;$
      ds.attrib["bathymetry_source"] = "GEBCO Compilation Group (2020) GEBCO 2020 Grid (doi:10.5285/a29c5465-b138-234d-e053-6c86abc040b9)"]
      ds.attrib["Acknowledgements"] = "Aggregated data products are generated by EMODnet Chemistry under the support of DG MARE Call for Tenders EASME/EMFF/2016/006-lot4, EASME/2019/OP/0003-lot4." ;
      ds.attrib["project"] = "EMODnet Chemistry - Phase 4" ;
    end
  
  end

datafilelist = glob("*.nc", databasedir)

for datafile in datafilelist
    @info("Workin on file $(datafile)")

    nccommand = `ncatted -a history,global,d,, "$(datafile)" "$(datafile)"`
	run(nckscommand);
    nccommand = `ncatted -a data_access,global,d,, "$(datafile)" "$(datafile)"`
	run(nckscommand);
    nccommand = `ncatted -a WEB_visualisation,global,d,, "$(datafile)" "$(datafile)"`
	run(nckscommand);

end
