"""Add new attributes to all the files:
- bathymetry
- DIVAnd source
- project
...
"""

include("./emodnetchemistry.jl")
using NCDatasets

# Flags for the editing
delete_valid_attrib = false
edit_global_attrib = true

# Files and directories
datadir = "/production/apache/data/emodnet-domains/By sea regions//Mediterranean Sea/"
datafilelist = get_file_list(datadir)

@info("Processing $(length(datafilelist)) file(s)");

function get_varname(datafile::String)
  varname = replace(basename(datafile), ".4Danl.nc" => "")
  return varname::String
end

function edit_global_att(datafile::String)
  NCDatasets.Dataset(datafile, "a") do ds
    ds.attrib["Conventions"] = "CF-1.6" ;
    ds.attrib["product_version"] = "2.0" ;
    ds.attrib["source"] = "Observational data from SeaDataNet/EMODnet Chemistry Data Network" ;
    ds.attrib["bathymetry_source"] = "The GEBCO 30sec Digital Atlas published by the British Oceanographic Data Centre on behalf of IOC and IHO, 2003" ;$
    ds.attrib["bathymetry_source"] = "GEBCO Compilation Group (2020) GEBCO 2020 Grid (doi:10.5285/a29c5465-b138-234d-e053-6c86abc040b9)"]
    ds.attrib["documentation"] = "10.6092/4e85717a-a2c9-454d-ba0d-30b89f742713" ;
    ds.attrib["Acknowledgements"] = "Aggregated data products are generated by EMODnet Chemistry under the support of DG MARE Call for Tenders EASME/EMFF/2016/006-lot4, EASME/2019/OP/0003-lot4." ;
    ds.attrib["DIVAnd_source"] = "https://github.com/gher-ulg/DIVAnd.jl" ;
    # ds.attrib["DIVAnd_version"] = "2.6.6" ;
    ds.attrib["DIVAnd_code_doi"] = "10.5281/zenodo.4715361" ;
    ds.attrib["DIVAnd_references"] = "Barth, A.; Beckers, J.-M.; Troupin, C.; Alvera-Azcárate, A. & Vandenbulcke, L. divand-1.0: n-dimensional variational data analysis for ocean observations. Geoscientific Model Development, 2014, 7, 225-241. DOI: :10.5194/gmd-7-225-2014" ;
    ds.attrib["project"] = "EMODnet Chemistry - Phase 4" ;
  end

end


for datafile in datafilelist
  @info("Working on file $(basename(datafile))")
  varname = get_varname(datafile)

  if delete_valid_attrib
    @debug("Variable name: $(varname)")
    remove_attribs(datafile, varname)
  end

  if edit_global_attrib
    NCDatasets.Dataset(datafile, "a") do ds
      attrib2delete = ["file_name", "data_access", "WEB_visualisation", "production"]
      attrib_dict = Dict(ds.attrib)

      # Loop on attributes to delete
      for attname in attrib_dict
        if haskey(attrib_dict, attname)
          @info("Remove global attribute: $(attname)")
          delete!(ds.attrib, attname)
        end
      end

    end
  end

end
