# edit_mergedfiles_attrib.jl
# Modify the attributes of the merged files
# as required by the Central Portal

include("MergingClim.jl")
using NCDatasets
using Glob
using DataStructures

datadir = "/production/apache/data/emodnet-test-charles/merged/"
regionlist = readdir(datadir);

comment_region = OrderedDict(
	"Arctic Ocean" => "Every year of the time dimension corresponds to a 6-year running average for Winter (December - February), Spring (March - May), Summer (June - August) or Autumn (September - November). Horizontal resolution 0.2° X 0.2°.",
	"Baltic Sea" =>   "Every year of the time dimension corresponds to a 6-year running average for Winter (December - February), Spring (March - May), Summer (June - August) or Autumn (September - November). Horizontal resolution 0.1° X 0.1°.",
	"Black Sea" =>    "Every year of the time dimension corresponds to a 6-year running average for Winter (December - February), Spring (March - May), Summer (June - August) or Autumn (September - November). Horizontal resolution 0.05° X 0.05°.",
	"Mediterranean Sea" => "Every year of the time dimension corresponds to a 6-year running average for Winter (January - March), Spring (April - June), Summer (July - September) or Automn (October - December). Horizontal resolution 0.125° X 0.125°.",
	"Northeast Atlantic Ocean" => "Every year of the time dimension corresponds to a 6-year running average for Winter (January - March), Spring (April - June), Summer (July - September) or Automn (October - December). Horizontal resolution 0.1° X 0.1°.",
	"North Sea" => "Every year of the time dimension corresponds to a 6-year running average for Winter (December - February), Spring (March - May), Summer (June - August) or Autumn (September - November). Horizontal resolution 0.1° X 0.1°."
)

for region in regionlist
	@info("Working on region $(region)");

	datafilelist = basename.(glob("*.nc", joinpath(datadir, region)))

	# Loop on the files
	for datafile in datafilelist
		@info("Working on file $(basename(datafile))");

		# Create a dictionary with the new attributes
		attrib_dict = OrderedDict(
			"comment" => comment_region[region],
			"file_name" => "$(region)/$(datafile)",
			"project" => "EMODnet Chemistry - Phase 4",
			"acknowledgement" => "Aggregated data products are generated by EMODnet Chemistry under the support of DG MARE Call for Tenders MARE/2008/03-lot3, MARE/2012/10-lot4,EASME/EMFF/2016/006-lot4, EASME/2019/OP/0003-lot4."
		)
		@debug(attrib_dict);
		@info("$(region)/$(datafile)");
		
		# Edit the attributes of the netCDF
		NCDatasets.Dataset(joinpath(datadir, region, datafile), "a") do ds
		 	for (key, value) in attrib_dict
		  		ds.attrib[key] = value
		  	end
		end
	end
end


#For the North Sea:
#"Moving 6-year analysis and visualization of Water body phosphate in the North Sea. Data Sources: observational data from SeaDataNet/EMODnet Chemistry Data Network. Description of DIVA analysis: Geostatistical data analysis by DIVAnd (Data-Interpolating Variational Analysis) tool, version 2.7.2. results were subjected to the minfield option in DIVAnd to avoid negative/underestimated values in the interpolated results; error threshold masks L1 (0.3) and L2 (0.5) are included as well as the unmasked field. The depth dimension allows visualizing the gridded field at various depths."