# edit_mergedfiles_attrib.jl
# Modify the attributes of the merged files
# as required by the Central Portal

include("MergingClim.jl")
using NCDatasets
using Glob

datadir = "/production/apache/data/emodnet-test-charles/merged/"
regionlist = readdir(datadir);

for region in regionlist
	@info("Working on file $(region)");

	datafilelist = basename.(glob("*.nc", joinpath(datadir, region)))

	# Loop on the files
	for datafile in datafilelist
		@info("Working on file $(basename(datafile))");

		NCDatasets.Dataset(joinpath(datadir, region, datafile), "r") do ds
			oldcomment = ds.attrib["comment"]
			@show(oldcomment);
		end

	end


end

# Create dictionary with the new values of the global attributes

attrib_dict = Dict(
	"product_id" => "9d09a580-f7b0-11e8-a9b9-f859715d4cd2",
	"comment" => "Every year of the time corresponds to a 6-year running average for the corresponding season: Autumn (Sep-Nov), Winter (Dec-Feb), Spring (Mar-May) and Summer (Jun-Aug). Horizontal resolution 0.2°.",
	#"documentation" => "10.6092/A8CFB472-10DB-4225-9737-5A60DA9AF523",
	#"doi" => "10.6092/c887f9f2-d6aa-4e73-8254-6a0b5963c08d",
	#"Acknowledgements" => "Aggregated data products are generated by EMODnet Chemistry under the support of DG MARE Call for Tenders MARE/2008/03-lot3, MARE/2012/10-lot4,EASME/EMFF/2016/006-lot4, EASME/2019/OP/0003-lot4.",
	"file_name" => "Arctic Ocean/Water_body_dissolved_oxygen_concentration.4Danl.nc",
	"project" => "EMODNET Chemistry - Phase 4",
)
