#!/bin/bash

param="Water_body_phosphate"
long_name="Water body phosphate"
unit="umol/l"

season="Spring (April-June) - 6-year running averages"
season="Summer (July-September) - 6-year running averages"
season="Winter (January-March) - 6-year running averages"

datafile="/production/apache/data/emodnet-domains/By sea regions/Northeast Atlantic Ocean/${season}/Water_body_phosphate.4Danl.nc"

if [ -f "$datafile" ]; then
  echo "Processing data file ${datafile}"
else
  echo "data file not found"
fi


var=$param
ncatted -h -a long_name,$var,o,c,"$long_name" -a units,$var,o,c,$unit "$datafile"

var="${param}_L1"
ncatted -h -a long_name,$var,o,c,"${long_name} masked using relative error threshold 0.3" -a units,$var,o,c,$unit "$datafile"

var="${param}_L2"
ncatted -h -a long_name,$var,o,c,"${long_name} masked using relative error threshold 0.5" -a units,$var,o,c,$unit "$datafile"

var="${param}_deepest"
ncatted -h -a long_name,$var,o,c,"Deepest values of ${long_name}" -a units,$var,o,c,$unit "$datafile"

var="${param}_deepest_depth"
ncatted -h -a long_name,$var,o,c,"Deepest depth for ${long_name}" -a units,$var,o,c,$unit "$datafile"


var="${param}_deepest_L1"
ncatted -h -a long_name,$var,o,c,"Deepest values of ${long_name} masked using relative error threshold 0.3" -a units,$var,o,c,$unit "$datafile"

var="${param}_deepest_L2"
ncatted -h -a long_name,$var,o,c,"Deepest values of ${long_name} masked using relative error threshold 0.5" -a units,$var,o,c,$unit "$datafile"

var="${param}_err"
ncatted -h -a long_name,$var,o,c,"Error standard deviation of ${long_name}" -a units,$var,o,c,$unit "$datafile"

var="${param}_relerr"
ncatted -h -a long_name,$var,o,c,"Relative error of ${long_name}" -a units,$var,o,c,$unit "$datafile"
